"""Close Phase X at the unchanged scientific gate, retaining real tiny fits."""
import collections,json
from jev_phase10_common import *
from gtr.modeling.jev_candidate_models import build_candidate_model


def main():
 protect();state=json.loads((REPORTS/'NATIVE_STATE_PARITY.json').read_text());h32=json.loads((REPORTS/'H32_CAUSAL_PARITY.json').read_text());data=json.loads((REPORTS/'DATA_ELIGIBILITY.json').read_text());assert state['status']=='PASS'and h32['status']=='PASS'and data['gate_pass']
 runs={};raw=[]
 for objective,folder in [('conditional_correctness_CE','tiny_v2'),('known_edge_binary_CE_diagnostic','tiny_binary_ce_diagnostic_v1'),('preregistered_joint_diagnostic','tiny_joint_diagnostic_v1')]:
  p=OUT/folder/'RESULT.json';d=json.loads(p.read_text());assert d['status'].startswith('FAIL_TINY')and d['steps_per_model']==2000 and not d['binding']['dirty'];models={}
  for name,m in d['models'].items():
   assert sha(m['checkpoint_path'])==m['checkpoint_SHA256'];assert m.get('permutation_candidate_choices_exact',m.get('permutation_choices_exact'))and m['scripted_training_normalization_exact'];assert m['final']['unknown_choice_rate']>=0
   models[name]={'actual_steps':2000,'history':m['history'],'final':m['final'],'checkpoint':{'path':m['checkpoint_path'],'SHA256':m['checkpoint_SHA256']},'permutation_choices_exact':True,'scripted_training_normalization_exact':True}
  runs[objective]={'status':d['status'],'source_commit':d['binding']['source_commit'],'source_root':d['binding']['source_root'],'GPU':d['binding']['CUDA_VISIBLE_DEVICES'],'JIT_runtime':d['JIT_runtime'],'models':models,'raw_result':{'path':str(p),'SHA256':sha(p)}};raw.append(runs[objective]['raw_result'])
  assert not all(m['final']['group_weighted_rank1']>=.95 for m in models.values()),'do not stop if all three models pass a common unchanged gate'
 selection=json.loads((OUT/'tiny_v1/SELECTION.json').read_text());assert len(selection['rows'])==12;diagnostic=json.loads((OUT/'tiny_v1/LABEL_NORMALIZATION_DIAGNOSTIC.json').read_text());assert diagnostic['status']=='INPUT_MASK_AND_NORMALIZATION_PASS'and not diagnostic['normalized_feature_label_collisions'];reason='STOP_TINY_FULL_LEGAL_CONFIRMED_CHOICE_GATE';names=['CandidateMLP','CandidateDeepSets','CandidateJEV'];capacities={}
 for name in names:
  model=build_candidate_model(name);capacities[name]={'parameters':sum(p.numel()for p in model.parameters()),'trainable_parameters':sum(p.numel()for p in model.parameters()if p.requires_grad)}
 tiny={'status':'FAIL_TINY_FIT_AFTER_BOUNDED_DIAGNOSTICS','reason':reason,'same_frozen12_TRAIN_rows8_original_groups':selection,'selection_SHA256':sha(OUT/'tiny_v1/SELECTION.json'),'full_legal_confirmed_rank1_gate':.95,'each_architecture_each_probe_actual_steps':2000,'actual_results':runs,'capacities':capacities,'input_mask_normalization_finite_permutation_scripted_parity_PASS':True,'normalized_label_collisions':[],'unknown_GT_not_negative_or_correct':True,'unexecuted_censored_Q_remains_unknown':True,'known_support_fit_is_not_full_legal_choice_qualification':True,'all_three_common_gate_pass':False,'new_rows_or_heldout_not_selected_to_pass':True,'formal_training':'NOT_RUN','heldout':'SEALED_NOT_RUN','raw_results':raw};save(REPORTS/'TINY_OVERFIT.json',tiny)
 for name,file in [('CandidateMLP','MLP_RESULTS.json'),('CandidateDeepSets','DEEPSETS_RESULTS.json'),('CandidateJEV','JEV_RESULTS.json')]:
  save(REPORTS/file,{'status':'TINY_COMPLETED_FORMAL_TRAINING_NOT_RUN','model':name,'capacity':capacities[name],'actual_tiny_results':{o:{'source_commit':d['source_commit'],'raw_result':d['raw_result'],**d['models'][name]}for o,d in runs.items()},'formal_three_seed20_50_100epoch_training':'NOT_RUN','validation_selection_calibration':'NOT_RUN','full_closed_loop_heldout':'NOT_RUN','reason':reason,'runtime_action_frequency':'NOT_MEASURED_FOR_LEARNED_FULL_CLOSED_LOOP','no_fake_tracking_or_generalization_results':True})
 save(REPORTS/'SUPERVISION_ABLATION.json',{'status':'BOUNDED_TINY_DIAGNOSTICS_COMPLETED_FORMAL_ABLATION_NOT_RUN','actual_tiny_results':runs,'original_conditional_correctness_protocol_preserved':True,'binary_CE_is_diagnostic_only_not_adopted_as_a_formal_change':True,'joint_supervision_is_originally_preregistered':True,'unknown_or_unexecuted_not_filled':True,'formal_equal_three_seed_comparison':'NOT_RUN','best_supervision_on_validation_or_heldout':'NOT_IDENTIFIED','reason':reason})
 save(REPORTS/'ARCHITECTURE_ABLATION.json',{'status':'NOT_RUN','reason':reason,'actual_main_architecture_tiny_results_reference':'TINY_OVERFIT.json','without_QA_without_context_without_causal_full_formal_runs':'NOT_RUN','capacity_contracts':'CANDIDATE_MODEL_CAPACITY_ABLATION_TESTS.json','WHO_constant_no_question_transfer_claim':True,'tiny_joint_difference_not_a_significance_or_generalization_result':True})
 save(REPORTS/'HELDOUT_RESULTS.json',{'status':'NOT_RUN','reason':reason,'videos':HELDOUT,'heldout_released':False,'freeze_manifest_created':(REPORTS/'PHASE10_CHECKPOINT_AND_HELDOUT_FREEZE.json').exists(),'full_mutated_state_online_model_tracking':'NOT_RUN','HOTA':None,'AssA':None,'IDF1':None,'MOTA':None,'IDSW':None,'Frag':None,'official_TEST':False,'Full24':False});assert not(REPORTS/'PHASE10_CHECKPOINT_AND_HELDOUT_FREEZE.json').exists();assert not(OUT/'heldout_closed_loop_v1').exists()and not(OUT/'fair_training_v1').exists()
 changedtags=dict(collections.Counter(d['tag']for d in h32['old_vs_new']));joint=runs['preregistered_joint_diagnostic'];metrics={n:joint['models'][n]['final']for n in names};answers={
 '1_gallery_parity':{'classification':'ENGINEERING_AND_NATIVE_CAUSAL_PARITY_PASS','answer':'全部221个原固定前缀通过，包含原94个失败记录；全部162事件/840分支的CONTROL和显式KEEP完整状态、事件、RNG等价。'},
 '2_H32_changes':{'classification':'REQUALIFIED_V3_NATIVE_LABELS','changed_branches':h32['changed_branches'],'changed_event_rows':h32['changed_event_rows'],'changed_actions':changedtags,'verified_corrections':data['verified_corrections'],'answer':'53个分支标签变化：52个START_NEW、1个REASSOCIATE。纠错数量重新核验后仍为训练74、验证59；相同数量不代表效用标签未变化。变化来自完整原生状态/转换契约替换旧Replay，不能全归因为某一条Gallery向量。'},
 '3_MLP':{'classification':'KNOWN_SUPPORT_TINY_FIT_PASS_FULL_LEGAL_QUALIFICATION_FAIL','joint_full_legal_confirmed_rank1':metrics['CandidateMLP']['group_weighted_rank1'],'joint_unknown_choice_rate':metrics['CandidateMLP']['unknown_choice_rate'],'answer':'MLP确实完成了真实tiny训练，已知候选与已执行效用对比可以拟合；联合目标下完整合法候选的已确认命中率68.59%，未达95%。不能把未知候选判作错误GT，也不能把它算作正确恢复；真实闭环纠错能力尚未验证。'},
 '4_DeepSets_vs_MLP':{'classification':'TINY_DIFFERENCE_ONLY_FORMAL_COMPARISON_NOT_RUN','answer':'联合tiny下DeepSets达到100%，MLP为68.59%；这仅是同一小样本的拟合差异，没有完整三seed/validation/heldout比较，不能宣称显著优于MLP。'},
 '5_JEV_vs_ordinary':{'classification':'ARCHITECTURE_SUPERIORITY_NOT_ESTABLISHED','answer':'联合tiny中JEV与DeepSets均为100%，没有已观察到的额外tiny优势。正式相同预算的闭环比较尚未执行，JEV独特结构优势未得到证明。'},
 '6_supervision':{'classification':'BOUNDED_TINY_DIAGNOSTIC_ONLY','answer':'正确性CE和已知边二元CE都不能使三模型达到完整合法候选门槛；原计划的联合监督使DeepSets/JEV通过该tiny指标，但MLP仍失败。可以记录其小样本作用，不能据此选择最优泛化监督。'},
 '7_Unified_JEV':{'classification':'NO_GO_FOR_UNIFIED_EXTENSION','answer':'目前没有足够证据扩展MATCH–MEMORY–REACTIVATION Unified JEV。下一步应先审计未锚定候选的身份语义与可验证监督支持；不得用GT泄漏、把未知改负、重新挑选有利tiny组或降低门槛来继续。'} }
 final={'status':'COMPLETE_SCIENTIFIC_STOP_AT_TINY_GATE','reason':reason,'state_gate_PASS':True,'H32_gate_PASS':True,'dataset_gate_PASS':True,'all_three_tiny_gate_PASS':False,'formal_training_or_closed_loop_architecture_hypothesis':'NOT_TESTED','seven_answers':answers,'original_gate_not_lowered':True,'ordinary_engineering_failures_repaired_before_stop':['per-model history indentation','CUDA JIT fusion resumed-kernel stall','native production gallery/state recovery'],'scientific_stop_is_distinct_from_engineering_errors':True,'actual_tiny_checkpoints_retained_and_SHA_bound':True,'heldout_sealed':True,'phase_V_to_IX_results_and_B2_unchanged':True,'official_TEST':False,'Full24':False,'required_outputs_completed_for_conditional_scientific_stop':True};save(REPORTS/'FINAL_GO_NO_GO.json',final)
 table='| 目标（共同2000步） | MLP已确认Rank-1 | DeepSets已确认Rank-1 | JEV已确认Rank-1 |\n|---|---:|---:|---:|\n'
 for o,d in runs.items():table+='| '+o+' | '+' | '.join(f'{d["models"][n]["final"]["group_weighted_rank1"]*100:.2f}%'for n in names)+' |\n'
 experiment='# Phase X 三模型实际实验与停止门槛\n\n原生状态、H32和v3数据门槛均通过，随后实际训练了三个约34K参数模型。固定TRAIN12/13/14/16的12行、8个原组；相同state64/evidence12、完整合法候选、TRAIN-only归一化、双头、seed20261008、AdamW0.001/weight_decay1e-4/clip5。每次诊断每个架构均为500步，必要时共同扩展到预声明的2000步；没有给JEV独占标签或预算。\n\n'+table+'\n正确性CE原实验与二元CE诊断均保留。联合目标使用原计划的正确性CE和已执行、未censor的H32偏好排序，任务均值1:1、部署双头和；未执行Q为NaN且不进入梯度。GT未知不标负，也不计正确。所有模型数值有限、候选排列选择不变、训练与TorchScript归一化一致；CUDA融合运行问题已在正式学习之前通过统一关闭融合修复。早期tiny历史缩进错误及其500步checkpoint也保留。\n\n全部三模型必须达到95%的完整合法集合已确认Rank-1。联合目标下MLP仍为68.59%，其中31.41%的加权选择属于身份锚点未知的候选；已知支持上的NLL和已执行对比拟合不能替代完整合法选择的认证。这不是证明这些未知候选GT错误，也不是架构能力上限的证明。\n\n因此正式三seed/20–50–100epoch、validation选择/校准、结构消融和heldout完整闭环均NOT_RUN。Tiny模型是实际训练的局部诊断，不能当作正式模型结果。每个checkpoint的服务器绝对路径、SHA、源码commit、样本选择SHA和完整原始结果来源在MLP_RESULTS/DEEPSETS_RESULTS/JEV_RESULTS、TINY_OVERFIT和SUPERVISION_ABLATION中记录；大文件未上传GitHub。\n'
 (ROOT/'docs/PHASE10_THREE_MODEL_EXPERIMENT.md').write_text(experiment)
 comparison='# Phase X 架构比较的证据边界\n\n同证据、约34K参数、双头、相同候选上下文与mask的实现测试通过。实际联合tiny中DeepSets与JEV都为100%，MLP为68.59%。这组训练样本既不能证明DeepSets的泛化显著优势，也没有证明JEV独特结构比DeepSets更好。没有三seed完整闭环或真正pooled TrackEval结果，HOTA/AssA等不填造数值。\n\nQ/A、候选上下文与因果头的完整训练消融NOT_RUN；仅容量、动态集合、空集合、全mask、排列和原生提交接口测试已通过。WHO/OLD是常量，不能据此宣称问题条件化迁移或Unified JEV。已知标签拟合很低损失而合法动作选中未锚定候选，说明监督覆盖与完整选择认证之间仍有缺口；不能把未知当负来掩盖此问题。\n'
 (ROOT/'docs/PHASE10_ARCHITECTURE_COMPARISON.md').write_text(comparison)
 report='# Phase X 最终科研报告\n\n最终状态：`COMPLETE_SCIENTIFIC_STOP_AT_TINY_GATE`。工程修复、原生H32和v3资格审查完成；固定的三模型共同tiny门槛未通过，后续正式训练与sealed heldout按用户预定规则停止。\n\n221/221原前缀通过，包括原94个失败快照。162事件/840原分支已从真实生产前缀逐个执行，CONTROL/显式KEEP在全部未来窗口的完整状态、事件和RNG与事实流精确匹配。53分支/53事件行的效用或错误持续标签变化（START_NEW52，REASSOCIATE1），旧标签和V–IX结论未覆盖。重新核验训练纠错74、验证59，原组17/9；v3共226行，TRAIN132/validation94。TRAIN Recall@8=97.56%、@16=98.37%、@32/64/Full=100%，未截断候选。\n\n'+table+'\n已完成三种有界目标的真实tiny学习，未完成正式三seed/validation/heldout架构比较。未知选择是未认证，不等于已知GT错误；不能用已知支持上的近零损失证明完整决策可靠。模型输入和归一化没有精确标签冲突，有限值、mask、候选排列、TorchScript及原生分段恢复已检查；保留所有早期故障和checkpoint。本次不会修改未知标签、填零Q、换容易样本、降低95%或扩展Full24来得到通过结果。\n\n'
 for key,d in answers.items():report+=f'## {key}\n\n{d["answer"]}\n\n'
 report+='复现入口：`capture_jev_phase10_production.py` → `check_jev_phase10_prefix_parity.py` → `run_jev_phase10_native_forks.py` → `finalize_jev_phase10_data.py` → `tiny_jev_phase10_candidates.py`；两次有界目标诊断由`diagnose_jev_phase10_tiny_objective.py`及其冻结protocol绑定。精确运行源码根、commit、GPU、seed、config/cache/foundation/B2 SHA与checkpoint路径均在JSON manifest。large native states、数据张量、完整分支日志和tiny权重留在独立服务器runtime；GitHub仅提交必要代码、compact指标、文档和SHA。\n'
 (ROOT/'docs/PHASE10_FINAL_RESEARCH_REPORT.md').write_text(report)
 contract=ROOT/'docs/PHASE10_NATIVE_STATE_CONTRACT.md';text=contract.read_text();text=text.replace('H32 future causal validity remains a separate pending gate.','The separate H32 gate now PASS: all162 frozen events/all840 branches re-executed with exact CONTROL/explicitKEEP full native future states/events/RNG. Dataset v3 passes its independently requalified eligibility gate; later model qualification stops at the unchanged all-three tiny gate.');contract.write_text(text)
 repair=ROOT/'docs/PHASE10_GALLERY_REPAIR_REPORT.md';text=repair.read_text();text=text.replace('Those remain gated until all frozen counterfactual branches run again.','All162 events/all840 frozen branches have now actually run again, and H32_CAUSAL_PARITY is PASS.53 branch labels changed; the change is a whole native-state/transition repair, not an isolated gallery-vector causal attribution. Learning reaches the tiny stage and stops at its separate unchanged qualification gate.');repair.write_text(text)
 datasetdoc=ROOT/'docs/PHASE10_CAUSAL_DATASET_V3.md';datasetdoc.write_text(datasetdoc.read_text()+'\nAll three models then completed bounded actual tiny fits. The dataset stays frozen and eligible; later full-legal model qualification fails for MLP, so formal training and heldout are NOT_RUN. Data eligibility is not proof of complete supervised action support or architecture generalization.\n')
 print('PHASE10_ALL_REQUIRED_SCIENTIFIC_STOP_OUTPUTS_COMPLETE',reason,flush=True)
if __name__=='__main__':main()
