"""Bind completed real models, shared selection and subsequent closed loops."""
import json,collections
from jev_phase10_common import *

def main():
 protect();complete=json.loads((OUT/'TRAINING_COMPLETE.json').read_text());assert complete['status']=='COMPLETE'and complete['all45_runs_complete'];epochs=complete['final_common_epochs'];results=collections.defaultdict(list);raw=[]
 for name in complete['models']:
  for supervision in complete['supervisions']:
   for seed in complete['seeds']:
    p=OUT/'fair_training_v1'/name/supervision/f'seed{seed}'/f'RESULT_{epochs:03d}.json';r=json.loads(p.read_text());assert r['status']=='COMPLETE'and r['budget_epochs']==epochs
    for field in ['best_checkpoint','last_checkpoint','scripted_calibrated_model']:assert sha(r[field]['path'])==r[field]['SHA256']
    assert not r['binding']['dirty'];assert r['binding']['source_commit']==complete['source_commit'];raw.append({'path':str(p),'SHA256':sha(p),'model':name,'supervision':supervision,'seed':seed});results[name].append(r)
 selection={}
 for name,rs in results.items():
  values={s:sum(r['VALIDATION']['selection_NLL']for r in rs if r['supervision']==s)/3 for s in complete['supervisions']};best=min(values,key=lambda s:(values[s],complete['supervisions'].index(s)));selection[name]={'supervision':best,'selection_mean_NLL':values,'criterion':'mean calibrated validation group-weighted deployment-preference correctness NLL over three seeds'}
 compact={name:[{k:v for k,v in r.items()if k not in ['TRAIN','VALIDATION','history','binding']}|{'TRAIN':{k:v for k,v in r['TRAIN'].items()if k!='records'},'VALIDATION':{k:v for k,v in r['VALIDATION'].items()if k!='records'},'source_commit':r['binding']['source_commit'],'source_result':str(OUT/'fair_training_v1'/name/r['supervision']/f'seed{r["seed"]}'/f'RESULT_{epochs:03d}.json'),'runtime_action_frequency':'NOT_MEASURED_BY_OFFLINE_RANKING; actual native closed-loop follows'}for r in rs]for name,rs in results.items()}
 for name,file in [('CandidateMLP','MLP_RESULTS.json'),('CandidateDeepSets','DEEPSETS_RESULTS.json'),('CandidateJEV','JEV_RESULTS.json')]:save(REPORTS/file,{'status':'COMPLETE_OFFLINE_TRAINING','model':name,'runs':compact[name],'selection':selection[name],'same_input_mask_heads_NEW_solver_normalization_optimizer':True,'runtime_closed_loop':'PENDING','heldout_sealed':True})
 save(REPORTS/'SUPERVISION_ABLATION.json',{'status':'COMPLETE_OFFLINE_TRAINING','supervisions':complete['supervisions'],'models':{n:compact[n]for n in complete['models'][:3]},'selection':selection,'tracking_supervision_comparison':'PENDING_FROZEN_CLOSED_LOOP','all_models_have_two_heads':True,'loss_task_weights':[1,1],'unexecuted_unknown_censored_utility_masked':True,'heldout_sealed':True})
 save(REPORTS/'ARCHITECTURE_ABLATION.json',{'status':'COMPLETE_OFFLINE_TRAINING','models':{n:compact[n]for n in complete['models'][3:]},'JEV_without_causal_utility':'CandidateJEV correctness-only runs in JEV_RESULTS.json; not duplicated','primary_structure_supervision':selection['CandidateJEV']['supervision'],'capacity_matched':True,'WHO_is_constant_no_question_transfer_claim':True,'heldout_sealed':True})
 save(REPORTS/'THREE_MODEL_TRAINING_COMPLETE.json',{'status':'COMPLETE','all45_actual_runs':True,'final_common_epochs':epochs,'models':complete['models'],'supervisions':complete['supervisions'],'seeds':complete['seeds'],'selection':selection,'raw_results':raw,'dataset_SHA256':results['CandidateMLP'][0]['dataset_SHA256'],'source_commit':complete['source_commit'],'calibration_completed_for_every_run':True,'heldout_sealed':True})
 cases=[{'name':'GMT_OFF','kind':'off'},{'name':'Fixed','kind':'rule','policy':'gmt_values'},{'name':'Bidirectional','kind':'rule','policy':'bidirectional_fixed_new'}]
 amendment=json.loads((REPORTS/'PHASE10_CAPACITY_AND_STRONG_RULE_AMENDMENT.json').read_text())
 for alpha in amendment['changes']['dynamic_alpha_grid']:cases.append({'name':f'Dynamic_alpha{alpha:g}','kind':'rule','policy':'dynamic_fixed_new','alpha':alpha})
 for name,rs in results.items():
  for r in rs:
   if name in complete['models'][3:]and r['supervision']!=selection['CandidateJEV']['supervision']:continue
   cases.append({'name':f'{name}_{r["supervision"]}_seed{r["seed"]}','kind':'model','architecture':name,'supervision':r['supervision'],'seed':r['seed'],'policy':'model_fixed_new','checkpoint':r['scripted_calibrated_model'],'capacity':r['capacity']})
 protocol={'status':'FROZEN_BEFORE_VALIDATION_CLOSED_LOOP','validation_videos':VAL,'heldout_videos':HELDOUT,'heldout_still_sealed':True,'cases':cases,'all_primary_architectures_all3_supervisions_all3_seeds_included':True,'structural_ablations_use_JEV_selected_supervision':True,'rule_selection':'highest true pooled validation HOTA; ties choose smallest alpha','learned_selection':selection,'same_native_solver_and_confidence_anchor':True,'no_heldout_selection':True,'Full24':False,'official_TEST':False};save(REPORTS/'PHASE10_VALIDATION_CONTROLLER_PROTOCOL.json',protocol)
 (ROOT/'docs/PHASE10_THREE_MODEL_EXPERIMENT.md').write_text(f'# Fair candidate model experiment\n\nAll 45 architecture/supervision/seed combinations completed real training and calibration, at a common {epochs}-epoch budget. Three main architectures and two structural ablations use approximately34K active parameters, identical current evidence, two heads, legal masks, TRAIN-only frozen normalization, fixed NEW and the enhanced native assignment/commit interface.\n\nSupervision compares conditional known-candidate correctness CE, only executed uncensored H32 preference ranking, and their equally weighted task means. Unknown Q remains unknown. Mean calibrated validation NLL over three seeds selects supervision equally for every architecture. Checkpoint hashes, actual parameters/MAC upper bounds, training histories and strata/calibration metrics are preserved in local result files bound by the compact reports.\n\nAll three main supervision variants proceed to the frozen tracking comparison; structural ablations use the JEV-selected supervision. Dynamic threshold rules are selected on validation pooled HOTA. Heldout remains sealed until actual validation, all checkpoint hashes and controller settings are frozen. WHO is constant, so this experiment cannot prove query transfer. Offline ranking/fit is separate from native online correction and generalization.\n')
 print('ACTUAL_45_RUNS_VERIFIED',epochs,'validation_cases',len(cases),flush=True)
if __name__=='__main__':main()
