"""Seven scientific answers from complete frozen experiments, or hard gates."""
import collections,itertools,json
import numpy as np
from jev_phase10_common import *
from finalize_jev_phase10_validation import collect

METRICS=['HOTA','AssA','IDF1','MOTA','IDSW','Frag']

def family(results,names):
 rs=[results[n]for n in names];summary={}
 for metric in METRICS:
  values=[r['pooled_metrics'][metric]for r in rs];summary[metric]={'mean':float(np.mean(values)),'std_population':float(np.std(values)),'by_seed_or_rule':values}
 pervideo={str(v):{metric:float(np.mean([r['per_video'][str(v)]['metrics'][metric]for r in rs]))for metric in METRICS}for v in HELDOUT};counts=collections.Counter();lat=[];memory=[];h32=[]
 for r in rs:
  for d in r['per_video'].values():
   counts.update(d['online_candidate_lifecycle_audit']['counts']);h32.append(d['paired_H32_causal_audit'])
   if d['extra_paired_latency_ms']:lat.append(d['extra_paired_latency_ms']['p95'])
   if d['extra_peak_VRAM_MiB']:memory.append(d['extra_peak_VRAM_MiB']['max'])
 return {'cases':names,'pooled_mean_and_seed_spread':summary,'per_video_seed_mean':pervideo,'online_counts_summed_over_optimization_replications':dict(counts),'net_same_prefix_fixed_corrections':counts['N01_same_prefix_fixed_to_policy']-counts['N10_same_prefix_fixed_to_policy'],'worst_per_video_seed_p95_extra_ms':max(lat)if lat else None,'max_extra_peak_VRAM_MiB':max(memory)if memory else None,'paired_H32':h32,'seed_variation_not_additional_independent_videos':True}

def contrast(a,b):
 deltas={m:a['pooled_mean_and_seed_spread'][m]['mean']-b['pooled_mean_and_seed_spread'][m]['mean']for m in METRICS};video={str(v):{m:a['per_video_seed_mean'][str(v)][m]-b['per_video_seed_mean'][str(v)][m]for m in METRICS}for v in HELDOUT};values=[video[str(v)]['HOTA']for v in HELDOUT];bootstrap=[float(np.mean([values[i]for i in indices]))for indices in itertools.product(range(3),repeat=3)]
 return {'delta_pooled_seed_means':deltas,'per_video_delta_seed_means':video,'positive_HOTA_and_AssA_videos':sum(d['HOTA']>0 and d['AssA']>0 for d in video.values()),'video_resampling_diagnostic_mean_HOTA_delta_95_interval':list(map(float,np.quantile(bootstrap,[.025,.975]))),'uncertainty_scope':'exact three-video resampling of per-video mean HOTA differences; diagnostic only, not a confidence interval for official pooled HOTA. Seed spread describes optimization. Three independent videos cannot establish broad significance.'}

def blocked(reason):
 protect();gate=json.loads((REPORTS/'DATA_ELIGIBILITY.json').read_text());h32=json.loads((REPORTS/'H32_CAUSAL_PARITY.json').read_text());assert not gate['gate_pass']or reason=='FAIL_TINY_FIT_AFTER_BOUNDED_DIAGNOSTICS'
 names=['TINY_OVERFIT','MLP_RESULTS','DEEPSETS_RESULTS','JEV_RESULTS','SUPERVISION_ABLATION','ARCHITECTURE_ABLATION','HELDOUT_RESULTS']
 for name in names:
  path=REPORTS/(name+'.json')
  if path.exists():continue
  save(path,{'status':'NOT_RUN','reason':reason,'scientific_gate':gate,'heldout_remains_sealed':True,'no_fake_metrics':True})
 answers={'1_gallery_parity':'ENGINEERING_PASS: all221 original fixed records, including all94 prior failures, exact native state and bounded64/12 evidence PASS.','2_H32_changes':{'changed_branches':h32['changed_branches'],'changed_event_rows':h32['changed_event_rows'],'reason':'Legacy replay replaced by real ordered native galleries/history/bank/transitions; old evidence is preserved.','requalified':gate['verified_corrections']},'3_MLP':'EXPERIMENT_NOT_EXECUTED_BECAUSE_SCIENTIFIC_GATE; no fit or generalization claim.','4_DeepSets_vs_MLP':'EXPERIMENT_NOT_EXECUTED; not a rejected architecture hypothesis.','5_JEV_vs_ordinary':'EXPERIMENT_NOT_EXECUTED; no architecture superiority claim.','6_supervision':'EXPERIMENT_NOT_EXECUTED; available causal evidence alone does not choose supervision.','7_Unified_JEV':'NO_GO: no independent learned MATCH evidence; do not expand to Unified JEV on this dataset.'};save(REPORTS/'FINAL_GO_NO_GO.json',{'status':'COMPLETE_SCIENTIFIC_NO_GO','reason':reason,'seven_answers':answers,'heldout_not_opened':True,'phase_V_to_IX_unchanged':True,'official_TEST':False,'Full24':False})
 for file in ['PHASE10_THREE_MODEL_EXPERIMENT.md','PHASE10_ARCHITECTURE_COMPARISON.md']:(ROOT/'docs'/file).write_text(f'# Phase X scientific gate\n\nStatus: NOT_RUN. {reason}. The frozen data eligibility checks are {gate["checks"]}. Ordinary implementation tests are not evidence that a candidate model works. No heldout result or architecture ordering is fabricated.\n')
 (ROOT/'docs/PHASE10_FINAL_RESEARCH_REPORT.md').write_text('# Phase X final scientific report\n\nNative engineering parity passed all221 original records; all162 events/840 frozen actions were actually re-executed. The next scientific gate prevents unsafe downstream claims.\n\n'+json.dumps(answers,ensure_ascii=False,indent=2)+'\n');print('PHASE10_HARD_GATE_FINALIZED',reason,flush=True)


def main():
 protect();assert json.loads((OUT/'HELDOUT_COMPLETE.json').read_text())['status']=='COMPLETE';freeze=heldout_guard(HELDOUT[0]);results,raw=collect('heldout',freeze['cases'],HELDOUT);selection=freeze['learned_selection'];families={}
 for architecture in ['CandidateMLP','CandidateDeepSets','CandidateJEV','CandidateJEV_without_QA','CandidateJEV_without_context']:
  supervision=selection[architecture if architecture in selection else'CandidateJEV']['supervision']if architecture in ['CandidateMLP','CandidateDeepSets','CandidateJEV']else selection['CandidateJEV']['supervision'];names=[c['name']for c in freeze['cases']if c.get('architecture')==architecture and c['supervision']==supervision];assert len(names)==3;families[architecture]=family(results,names)
 for c in freeze['cases']:
  if c['kind']!='model':families[c['name']]=family(results,[c['name']])
 ordinary=family(results,freeze['strongest_ordinary_validation']['cases']);jev=families['CandidateJEV'];primary=contrast(jev,ordinary);d=primary['delta_pooled_seed_means'];threshold=freeze['architecture_gate'];checks={'pooled_HOTA_at_least_point1':d['HOTA']>=threshold['HOTA_points'],'pooled_AssA_at_least_point2':d['AssA']>=threshold['AssA_points'],'at_least_two_positive_videos':primary['positive_HOTA_and_AssA_videos']>=2,'corrections_not_canceled':jev['net_same_prefix_fixed_corrections']>=0,'p95_extra_ms_at_most10':jev['worst_per_video_seed_p95_extra_ms']is not None and jev['worst_per_video_seed_p95_extra_ms']<=10,'extra_VRAM_at_most128MiB':jev['max_extra_peak_VRAM_MiB']is not None and jev['max_extra_peak_VRAM_MiB']<=128};architecture_pass=all(checks.values());matched={}
 for supervision in ['correctness','H32_ranking','joint']:
  f={architecture:family(results,[c['name']for c in freeze['cases']if c.get('architecture')==architecture and c['supervision']==supervision])for architecture in ['CandidateMLP','CandidateDeepSets','CandidateJEV']};matched[supervision]={'families':f,'JEV_minus_MLP':contrast(f['CandidateJEV'],f['CandidateMLP']),'JEV_minus_DeepSets':contrast(f['CandidateJEV'],f['CandidateDeepSets']),'DeepSets_minus_MLP':contrast(f['CandidateDeepSets'],f['CandidateMLP'])}
 compact={name:{'case':r['case'],'pooled_metrics':r['pooled_metrics'],'per_video':{v:{k:d[k]for k in ['metrics','counts','online_candidate_lifecycle_audit','paired_H32_causal_audit','extra_paired_latency_ms','extra_peak_VRAM_MiB','identity_summary','identity_index_query']}for v,d in r['per_video'].items()},'raw_pooled_metrics':r['raw_pooled_metrics']}for name,r in results.items()};save(REPORTS/'HELDOUT_RESULTS.json',{'status':'COMPLETE','heldout_videos':HELDOUT,'true_TrackEval_pooling':True,'cases':compact,'raw_results':raw,'selected_families':families,'validation_selected_ordinary':ordinary,'frozen_checkpoint_and_control_SHA256':sha(REPORTS/'PHASE10_CHECKPOINT_AND_HELDOUT_FREEZE.json'),'official_TEST':False,'Full24':False})
 supervision_path=REPORTS/'SUPERVISION_ABLATION.json';supervision=json.loads(supervision_path.read_text());supervision.update(status='COMPLETE',tracking_supervision_comparison=matched,heldout_sealed=False,selection_unchanged=True);save(supervision_path,supervision)
 archpath=REPORTS/'ARCHITECTURE_ABLATION.json';architecture=json.loads(archpath.read_text());architecture.update(status='COMPLETE',selected_families=families,matched_supervision_comparisons=matched,JEV_minus_without_QA=contrast(jev,families['CandidateJEV_without_QA']),JEV_minus_without_context=contrast(jev,families['CandidateJEV_without_context']),heldout_sealed=False,selection_unchanged=True);save(archpath,architecture)
 for name,file in [('CandidateMLP','MLP_RESULTS.json'),('CandidateDeepSets','DEEPSETS_RESULTS.json'),('CandidateJEV','JEV_RESULTS.json')]:
  p=REPORTS/file;x=json.loads(p.read_text());x.update(status='COMPLETE',runtime_closed_loop=families[name],heldout_sealed=False,selection_unchanged=True);save(p,x)
 state=json.loads((REPORTS/'NATIVE_STATE_PARITY.json').read_text());h32=json.loads((REPORTS/'H32_CAUSAL_PARITY.json').read_text());data=json.loads((REPORTS/'DATA_ELIGIBILITY.json').read_text());dscontrast=contrast(families['CandidateDeepSets'],families['CandidateMLP']);bestheldout=max(['CandidateMLP','CandidateDeepSets','CandidateJEV'],key=lambda n:families[n]['pooled_mean_and_seed_spread']['HOTA']['mean']);best_supervision={architecture:max(matched,key=lambda s:matched[s]['families'][architecture]['pooled_mean_and_seed_spread']['HOTA']['mean'])for architecture in ['CandidateMLP','CandidateDeepSets','CandidateJEV']}
 answers={'1_gallery_parity':{'classification':'ENGINEERING_PASS','fixed_original_records':state['fixed_original_records'],'all_original94_failures_repaired':True},'2_H32_changes':{'classification':'CAUSAL_NATIVE_CONTRACT_PASS','changed_branches':h32['changed_branches'],'changed_event_rows':h32['changed_event_rows'],'verified_corrections':data['verified_corrections'],'cause':'Real ordered gallery, lifecycle and mutable future production transitions replace the legacy replay; old-vs-new effects retained.'},'3_MLP':{'classification':'ACTUAL_FIT_AND_HELDOUT_EVALUATED','result':families['CandidateMLP'],'native_corrections_measured_separately_from_tiny_fit':True},'4_DeepSets_vs_MLP':{'classification':'DESCRIPTIVE_3_VIDEO_COMPARISON_NO_BROAD_SIGNIFICANCE','comparison':dscontrast},'5_JEV_vs_ordinary':{'classification':'PREREGISTERED_ARCHITECTURE_GATE_PASS'if architecture_pass else'ARCHITECTURE_ADVANTAGE_NOT_SUPPORTED_BY_GATE','comparison':primary,'checks':checks,'best_heldout_family_descriptive_only':bestheldout},'6_supervision':{'classification':'ACTUAL_MATCHED_SUPERVISION_COMPARISON','validation_selection':selection,'best_heldout_supervision_descriptive_only_no_reselection':best_supervision},'7_Unified_JEV':{'classification':'CONDITIONAL_MATCH_EVIDENCE_ONLY'if architecture_pass else'NO_GO_UNIFIED_EXTENSION','answer':'MATCH gate supports a next independent MEMORY/REACTIVATION study, but does not prove Unified JEV.'if architecture_pass else'Do not expand the current JEV structure on an unproven architecture claim; retain useful ordinary candidate conditioning if it performs well.','WHO_constant_no_multi_question_transfer_proof':True}}
 final={'status':'COMPLETE_MATCH_ARCHITECTURE_GO'if architecture_pass else'COMPLETE_MATCH_ARCHITECTURE_NO_GO','architecture_gate_PASS':architecture_pass,'checks':checks,'strongest_ordinary_chosen_before_heldout':freeze['strongest_ordinary_validation'],'JEV_vs_validation_selected_ordinary':primary,'seven_answers':answers,'scientific_limits':['Only3 independent heldout videos; overlapping H32 windows and optimization seeds are not additional scenes.','All enhanced methods share one solver, evidence support and fixedNEW; GMT OFF rectangular reference has a different objective.','H32 regret is against an actually executed same-prefix Fixed alternative at one predeclared boundary per video/controller, not exhaustive oracle regret.','WHO/OLD are fixed constants; no query transfer or Unified lifecycle benefit is demonstrated.'],'phase_V_to_IX_unchanged':True,'official_TEST':False,'Full24':False};save(REPORTS/'FINAL_GO_NO_GO.json',final)
 comparison=f'# Native closed-loop architecture comparison\n\nStatus: {final["status"]}. All enhanced policies use identical values Hungarian, candidate masks, fixedNEW and actual mutable state commits. Main architectures have all3 supervision variants and3 optimization seeds.\n\nValidation-selected ordinary control: {freeze["strongest_ordinary_validation"]}. JEV minus this control: {d}. Preregistered gate: {checks}. Descriptive best heldout main architecture: {bestheldout}; this does not change selection. DeepSets minus MLP: {dscontrast["delta_pooled_seed_means"]}.\n\nTrackEval pooled results come from real COMBINED_SEQ over all six TRAIN-view sequences, not arithmetic averages of video HOTA. Optimization spread and three-video resampling diagnostics are reported separately. Three videos do not establish broad statistical significance. Direct same-prefix assignment corrections, full online contaminated-memory/error episodes, and executed paired H32 forks are separate evidence. H32 causal regret only compares the executed Fixed alternative at frame128/view0. WHO is constant; question transfer and Unified JEV remain untested.\n';(ROOT/'docs/PHASE10_ARCHITECTURE_COMPARISON.md').write_text(comparison)
 text='# Phase X final research report\n\n'+comparison.split('\n',1)[1]+'\nThe seven answers are machine-readable in FINAL_GO_NO_GO.json.\n\n'
 for key,value in answers.items():text+=f'## {key}\n\n'+json.dumps(value,ensure_ascii=False,indent=2)+'\n\n'
 (ROOT/'docs/PHASE10_FINAL_RESEARCH_REPORT.md').write_text(text);print('PHASE10_ACTUAL_RESEARCH_FINALIZED',final['status'],checks,flush=True)

if __name__=='__main__':
 import argparse;p=argparse.ArgumentParser();p.add_argument('--hard-gate-reason');a=p.parse_args();blocked(a.hard_gate_reason)if a.hard_gate_reason else main()
