"""Final evidence-led report; refuses incomplete required experiment matrices."""
import json,statistics,subprocess
from jev_phase12_common import *

def main():
    protect();required=['STRUCTURAL_TESTS','QUESTION_CONDITIONING_TESTS','OPTION_READER_TESTS','NATIVE_PARITY','SHADOW_MODE_TESTS','MATCH_TINY_RESULTS','MATCH_OFFLINE_VALIDATION','MATCH_VALIDATION_RESULTS','GLOBAL_MCMOT_VALIDATION','ARCHITECTURE_ABLATION','LIFECYCLE_DATA_ELIGIBILITY','ONLINE_LATENCY']
    for name in required:assert (REPORTS/(name+'.json')).exists(),name
    online=json.loads((REPORTS/'MATCH_VALIDATION_RESULTS.json').read_text());assert online['status']=='COMPLETE' and online['native_video_actors']==168
    offline=json.loads((REPORTS/'MATCH_OFFLINE_VALIDATION.json').read_text());global_data=json.loads((REPORTS/'GLOBAL_MCMOT_VALIDATION.json').read_text());assert global_data['status']=='COMPLETE' and len(global_data['cases'])==56
    latency=json.loads((REPORTS/'ONLINE_LATENCY.json').read_text());assert latency['status']=='COMPLETE'
    lifecycle=json.loads((REPORTS/'LIFECYCLE_DATA_ELIGIBILITY.json').read_text());byname={r['case']['name']:r for r in online['cases']};joint={r['case']['name']:r for r in global_data['cases']}
    visual_memory=lifecycle['MEMORY']['visual_future_followup'];assert visual_memory['status']=='COMPLETE'
    assert json.loads((REPORTS/'DELIVERY_INTEGRITY.json').read_text())['status']=='PASS'
    assert json.loads((REPORTS/'STALE_TYPED_INPUT_CONTRACT.json').read_text())['status']=='PASS'
    seeds=[20261008,20261009,20261010];main_models=['CandidateMLP','CandidateDeepSets','CandidateJEV','set_transformer','visual_deepsets','question_plain','full','numerical_only','full_no_risk']
    def records(name):return [byname[name]] if name in ['GMT_OFF','Fixed'] else [byname[f'{name}_s{s}'] for s in seeds]
    def avg(name,field,scope='strict_online'):return statistics.mean(r['pooled_metrics'][scope][field] for r in records(name))
    def global_avg(name,field):
        names=[name] if name in ['GMT_OFF','Fixed'] else [f'{name}_s{s}' for s in seeds]
        return statistics.mean(joint[n]['metrics']['strict_online']['metrics'][field] for n in names)
    def diagnostic_avg(name,field):return statistics.mean(r['diagnostics']['counts'].get(field,0) for r in records(name))
    full_hota=avg('full','HOTA');off_hota=avg('GMT_OFF','HOTA');set_hota=avg('set_transformer','HOTA');full_assa=avg('full','AssA');off_assa=avg('GMT_OFF','AssA')
    positive=full_hota>max(off_hota,avg('Fixed','HOTA'),set_hota) and full_assa>max(off_assa,avg('Fixed','AssA'),avg('set_transformer','AssA'))
    original_latency=latency['isolated_native_prefix_benchmark']['summaries'];fast=json.loads((REPORTS/'EXACT_TOKEN_OPTIMIZATION.json').read_text());fast_p95=[v['total_policy_and_feature_ms']['p95'] for n,v in fast['summaries'].items() if n.startswith('full')]
    known_delta=offline['paired_diagnostics']['set_transformer'];no_risk_hota=avg('full_no_risk','HOTA');risk_delta=full_hota-no_risk_hota
    gate={'status':'COMPLETE','implementation_gate':'PASS','dynamic_visual_question_option_contract':'PASS','native_GATE':'PASS_221_AND_GENUINE_COMMIT_AND_SPECIAL_ACTIONS','MATCH_training':'COMPLETE_9_TINY_AND51_FORMAL_FITS','validation':'COMPLETE_168_REAL_NATIVE_VIDEO_ACTORS','scientific_performance_gate':'DEVELOPMENT_GO' if positive else 'NO_GO','main_decision':'DO_NOT_EXPAND_CURRENT_MATCH_FOR_PERFORMANCE_CLAIMS' if not positive else 'DEVELOPMENT_EVIDENCE_ONLY','full_mean_strict_HOTA':full_hota,'GMT_OFF_strict_HOTA':off_hota,'full_minus_GMT_OFF_HOTA':full_hota-off_hota,'full_minus_Set_HOTA':full_hota-set_hota,'full_minus_GMT_OFF_AssA':full_assa-off_assa,'offline_full_minus_Set_certified_lower_bound':known_delta,'risk_on_minus_risk_off_HOTA':risk_delta,'latency_gate':'NO_GO_10MS_TARGET_UNMET' if max(fast_p95)>10 else 'OPTIMIZED_PREFIX_BENCHMARK_GO_PRIMARY_ONLINE_DEPLOYMENT_UNPROVEN','optimized_real_prefix_p95_range_ms':[min(fast_p95),max(fast_p95)],'MEMORY_training':{'status':'NOT_RUN','metrics':None,'reason':lifecycle['MEMORY']['status']},'REACTIVATION_training':{'status':'NOT_RUN','metrics':None,'reason':lifecycle['REACTIVATION']['status']},'SharedMultiQuestionTraining':{'status':'NOT_RUN','metrics':None,'reason':'two task data qualifications fail'},'FULL_LIFECYCLE':{'status':'NOT_RUN','metrics':None,'reason':'only MATCH has qualified supervision; MEMORY/REACT frozen native fallback'},'Heldout20_21_22':{'status':'NOT_RUN_SEALED','metrics':None,'reason':'scientific performance and deployment latency gates unmet'},'Full24':{'status':'NOT_RUN_UNAUTHORIZED','metrics':None},'official_TEST':{'status':'NOT_RUN_UNAUTHORIZED','metrics':None},'commercial_TypeSafe_or_RLCD_reproduction':False,'historical_PhaseX_Tiny_FAIL_preserved':True,'trained_architecture_or_weights_retuned_after_online_metrics':False,'scope':'3 development validation videos, 3 fitted seeds, partial labels; no confirmatory heldout significance claim'}
    save(REPORTS/'FINAL_GO_NO_GO.json',gate)
    lines=['# Phase XII — Visual System-One / Jev-style MCMOT research report','',f'结论：结构和原生执行接口验收通过，MATCH 完成真实训练；当前性能与部署科学 Gate 为 **{gate["scientific_performance_gate"]}**。Full 严格在线 HOTA 三种子均值 {full_hota:.3f}，GMT OFF {off_hota:.3f}，差值 {full_hota-off_hota:+.3f}。不能将结构成立写成结构收益成立。','',
        '本阶段从 Phase X `957644fa2e300388a603fb352f73917e385bcd24` 独立研究分支开始。Phase V–X 的源码提交、报告、B2 权重、221 前缀、840 分支、53 个修正 H32 标签与旧 Tiny FAIL 保持原样。heldout20/21/22 封存，未启动 Full24，未读取官方 TEST。','',
        '## 实际结构与证据','',
        '公开实现锁定 Valen `5f775c4f6747216d6085d088c9004af66371638d`、OmniJev `14dbec4f71e194852c8d7b88ab36ef639493f400`、Visual-Jev `a392eaedfa41adae348f9767b55c0f54b3a13b57`、NanoJev `76fdfc9ecdca45a9bcef17991a07d3041a87685a`；前三者 Apache-2.0，NanoJev MIT。路径、许可证与逐文件 SHA 见 [实际源码审计](JEV_PHASE12_EXTERNAL_ARCHITECTURE_AUDIT.md) 和 `EXTERNAL_CODE_MANIFEST.json`。没有宣称复现私有 TypeSafe Jev 或完整 RLCD。','',
        '```mermaid','flowchart TD',' P[Frozen GMT: cached current ReID + actual past Gallery] --> T[Native visual token builder]',' T --> S[Shared StateEncoder: 8 latent tokens, d128]',' S --> Q[Dynamic typed QuestionReader: current visual + context64]',' Q --> O[ActionOptionReader: own history + evidence12 + question/state reads]',' S --> O',' O --> G[Residual question-dependent tanh gate]',' G --> C[Typed choice / binary probabilities]',' G --> V[H8/H16/H32 consequence predictions]',' C --> R[Legal masks + frozen risk fallback]',' V --> R',' R --> A[Native lawful Hungarian: existing ID or DEFER]',' A --> B[Actual stale-bank reactivation / START_NEW]',' B --> M[Committed ID then native WRITE / KEEP]',' M --> N[Mutated Gallery, bank, hits, ID counter, RNG]',' N --> T','```','',
        '| 张量 | 实际维度与来源 |','|---|---|','| OnlineVisualState.visual | `[B,T,1152]`；当前检测 + 每个身份 recent/first-resident/gallery-mean 三个真实 token |','| metadata / mask | `[B,T,8]` / `[B,T]`；类型、Gallery 长度、真实可知时间/相机，未知标记明确 |','| StateMemory | `[B,8,128]`；一次状态编码服务同批 Q 个问题 |','| QuestionDescriptor | visual `[B,Q,1152]`、context `[B,Q,64]`、真实 task type/mask |','| QuestionState | `[B,Q,128]`；动态当前输入与问题到状态 cross-attention |','| ActionOptions | `[B,Q,K,3,1152]` + evidence12、history/legality mask；ID 仅为执行引用 |','| ActionRepresentation | `[B,Q,K,128]`；每个候选读取自己的问题、共享状态和竞争上下文 |','| Choice / Q | `[B,Q,K]` / `[B,Q,K,3]`；H8/H16/H32 输出为 TRAIN 标准化效用预测 |','',
        '实际 GMT 提供 1152D ReID，未假设 ROI patch tokens。历史 attention 长度固定为 3 个可解释视觉观测，每个身份的均值读取实际 Gallery；不对整个长期 Gallery 做 self-attention。first token 是当前 resident 第一元素，不承诺等于未经原生 promotion/alias 修改的初生向量。','',
        '源码在 `gtr/modeling/visual_jev_mcmot/`：`visual_state_encoder.py`、`typed_question_reader.py`、`action_option_encoder.py`、`option_reader.py`、`typed_decision_heads.py`、`consequence_value_head.py`、`lifecycle_controller.py`。普通 MLP、DeepSets 与旧静态 CandidateJEV 单独作为数值对照；旧两个输出增加同一 2→3 效用投影共 9 参数，不称为新版 Jev。','',
        'CPU/CUDA、K=0/1/2/7/41、动态 Q、空集合、合法动作类型、mask、nonfinite 拒绝、梯度与视觉敏感性、候选排列等变测试通过。受控“相同状态与视觉、不同动态问题产生不同正确动作”的功能任务，动态 Reader 100%，固定问题 50%；这证明功能路径，不能当作 MOT 成功。','',
        '原始 221 个前缀全部重新验证 OFF/SHADOW 的完整有序 Gallery/bank/hits/ID/RNG 与当前、下一帧提交。真实候选干预改变 committed ID、正确单次写入并改变下一步真正的候选分数。另以真实 stale-bank 引用证明 ABSTAIN 保持原生状态、DEFER 先查询 bank、恢复旧身份可避免 birth，START_NEW 才分配新 ID。强制动作测试为未训练工程验证，未充作科研性能或监督资格。','',
        '## 训练和离线开发集结果','',
        'Frozen native v3：TRAIN 132、Validation 94，verified correction 74/59；不是完整视频的代表性 IID 分类样本。视觉数据 SHA `67f6dcf5acca15c6fa63d20674e9b0c9c8151b7943bd2b354c699a48ca0629e1`。未执行 Q 保持 NaN，UNKNOWN 不作负例。归一化与多尺度效用缩放只用 TRAIN；checkpoint 根据已知范围 NLL + 已执行分支 ranking loss 选择，温度仅在已知候选范围拟合。独立 abstain head 未获得标签，实际采用事前冻结 confidence .55 / margin .10 风险规则。','',
        'Tiny：同一冻结 12 rows / 8 groups，3 supervision × 3 seeds，各 1000 updates。Joint 三种子均 100% 已确认正确；CE 第三种子保留 13.46% UNKNOWN，H32-only 保留错误。正式训练 17 conditions × 3 seeds，全部 100 epochs / 900 updates，数值稳定；没有删掉不利种子或以旧 all-model95% Tiny 门槛中止新协议。','',
        '| 方法 | 参数 | 训练示例 MAC | Certified Correct % | Certified Wrong % | UNKNOWN % | known NLL | executed H32 regret |','|---|---:|---:|---:|---:|---:|---:|---:|']
    for name in offline['models']:
        r=offline['models'][name];d=r['VALIDATION_mean'];c=r['seeds'][0]['capacity'];lines.append(f'| {name} | {c["params"]:,} | {c["MAC"]:,} | {d["CertifiedCorrect"]*100:.2f} | {d["CertifiedWrong"]*100:.2f} | {d["UNKNOWNChoice"]*100:.2f} | {d["known_NLL"]:.4f} | {d["executed_H32_regret"]:.4f} |')
    lines.extend(['','MAC 为实际冻结训练示例（最多16 rows、Q=1、padding）的线性/attention hook 计算，FLOPs(matmul)=2×MAC，排除 norm/softmax/GELU 和数据搬运；不是任意在线 K 的固定 FLOPs。Full/Set/视觉 DeepSets/plain 动态问题基线具有相同视觉与效用监督，主要基线容量相差不超过20%。原数值模型是新增信息对照。','',
        '固定问题/移除 Reader 等消融保留部分未使用参数，参数表报告 registered 数量，MAC 按实际 forward 执行计数。no_consequence 仍注册并计算头，但不使用其 loss 或推理 Q；它是功能消融，不是计算剪枝。numerical_only 的视觉张量为零，注册参数相同但视觉权重功能不活跃。','',
        f'Full 相对 Set 的已确认正确下界差 {known_delta["full_minus_baseline_certified_correct"]*100:+.2f} 个百分点；temporal-bundle paired bootstrap 95% 区间 {[round(x*100,2) for x in known_delta["temporal_bundle_bootstrap95"]]}。这只是 partial-label、同一3个视频上的诊断区间，不能称为完整身份准确率或独立 heldout 显著性。','',
        '![全部种子训练曲线](figures/JEV_PHASE12/MATCH_LEARNING_CURVES.png)','',
        '## 真实在线闭环','',
        '56 个冻结 controller 条件 × video17/18/19 = 168 个完整 native mutated-state 视频运行。每256帧原子记录 lossless 原生恢复点和进度；失败/中断尝试保留。原始输出含当时已提交 ID，作为严格在线主结果。GMT min_track_len=50 在完整视频结束后过滤，属于可使用未来长度信息的传统 benchmark 后处理，仅单独列作 secondary canonical 结果。','',
        '标准 TrackEval 合并6个 camera sequences，而非平均3个视频分数。新增 joint-camera scene 审计保持原始 GT 身份、坐标、检测与 native IDs，以 `(frame,camera)` 虚拟时序关联同场景两相机；它的 HOTA/AssA/IDF1 用于跨相机关联诊断，不是官方 camera-sequence benchmark 的替代。虚拟时序的 CLEAR IDSW/Frag 可受相机可见性和交替顺序影响，不能解释为物理时间错误传播。错误传播另按真实 camera-frame 的 prefix-confirmed 连续错误段计算，不假设 FPS。相同几何也不保证 DetA 完全相同：TrackEval HOTA 先以全局身份 alignment×IoU 做 Hungarian，跨相机合并会改变该匹配权重；两种 scope 的差值逐条件保留在 DELIVERY_INTEGRITY。','',
        '| 方法 | strict HOTA | strict AssA | IDF1 | IDSW | MOTA | Frag | joint-camera HOTA | joint AssA |','|---|---:|---:|---:|---:|---:|---:|---:|---:|'])
    for name in ['GMT_OFF','Fixed']+main_models:
        lines.append(f'| {name} | {avg(name,"HOTA"):.3f} | {avg(name,"AssA"):.3f} | {avg(name,"IDF1"):.3f} | {avg(name,"IDSW"):.1f} | {avg(name,"MOTA"):.3f} | {avg(name,"Frag"):.1f} | {global_avg(name,"HOTA"):.3f} | {global_avg(name,"AssA"):.3f} |')
    lines.extend(['','学习方法为三种子真实 pooled 指标的均值；每个 pooled 值来自重新运行 TrackEval COMBINED_SEQ，seed range、canonical、完整结构消融、纠错/反改错、false births/merges、跨相机 continuity、Gallery contamination、候选准确率上下界与真实错误段详见 `MATCH_VALIDATION_RESULTS.json`、`ARCHITECTURE_ABLATION.json`、`GLOBAL_MCMOT_VALIDATION.json`。','',
        '![全部冻结种子完整在线比较](figures/JEV_PHASE12/MATCH_ONLINE_COMPARISON.png)','',
        'Prefix-anchor 诊断只在前两个一致、已知的实际 association commits 后固定身份锚点；主相机初始化单独计数，不属于该 journal 的首次两次关联。标准与 joint TrackEval 都使用包含初始化的完整预测。UNKNOWN 不算正确或错误，candidate certificate 不能当成全视频 IDF1。原始 actor 文件中的初始化计数字段有 camera 选择错误；BOOTSTRAP_METADATA_CORRECTION 从真实首个 payload 和完整 raw 预测派生正确值，汇总记录修正，actor、预测、模型与指标均原样保留。','',
        '| 风险比较：三种子均值 | HOTA | prefix-confirmed wrong | anchor UNKNOWN | same-prefix Fixed 错→对 | same-prefix Fixed 对→错 |','|---|---:|---:|---:|---:|---:|'])
    for name in ['full','full_no_risk']:
        lines.append(f'| {name} | {avg(name,"HOTA"):.3f} | {diagnostic_avg(name,"confirmed_wrong_observations"):.1f} | {diagnostic_avg(name,"anchor_unknown"):.1f} | {diagnostic_avg(name,"N01_same_prefix_fixed_to_policy"):.1f} | {diagnostic_avg(name,"N10_same_prefix_fixed_to_policy"):.1f} |')
    lines.extend(['','Risk on/off 的完整状态轨迹不同，锚点资格范围也不同，不能仅凭已确认 wrong 更低/更高就把 UNKNOWN 当作错误或宣称所有错误概率下降。主 HOTA 差值和上述实际纠错/反改错一起报告。','',
        '| 全部结构条件 | HOTA mean | min–max seeds | AssA mean |','|---|---:|---:|---:|'])
    for name in list(offline['models'])+['full_no_risk']:
        vals=[r['pooled_metrics']['strict_online']['HOTA'] for r in records(name)]
        lines.append(f'| {name} | {statistics.mean(vals):.3f} | {min(vals):.3f}–{max(vals):.3f} | {avg(name,"AssA"):.3f} |')
    lines.extend(['','![真实闭环结构消融](figures/JEV_PHASE12/MATCH_ONLINE_ABLATIONS.png)','',
        '每个视频/controller 在事前固定 [128,0] 完整原生前缀做 current-payload Fixed 替代，之后采用同一个冻结 controller 在各自 mutated state 上重新计算未来候选。实际分支与完整在线轨迹提交 ID/hits/Gallery 长度相符。H32 regret 仅相对于这一实际执行过的替代，非所有候选的 oracle。训练效用标签来自 GMT_OFF 后续策略；部署未来策略变成 learned controller，有 background-policy 分布变化，不能称作 Bellman critic 或把单边 Q 相加当作真实 joint assignment value。','',
        '## 生命周期监督与延迟','',
        '原始4个 TRAIN 视频事前冻结最早两个真实 WRITE 事件，共8个 WRITE/KEEP H32/H64 原生分叉。GMT_OFF future 下8/8 Gallery 改变，0个目标后续 bank READ、0个后续原生 score/committed-ID 变化，H32/H64 全部 utility tie；原协议、报告V1和分支保持原样。','',
        f'新模型主动读取 Gallery，因此另行冻结 same8 事件、最小事前种子20261008，当前 MATCH 仍为 GMT_OFF 以保持真实 WRITE 事件，之后每个 payload 才启用冻结 Full MATCH_ONLY。{visual_memory["actual_visual_MATCH_READ_events"]}/8 事件真实读取目标视觉历史，{visual_memory["changed_visual_MATCH_READ_events"]}/8 读取改变，{visual_memory["changed_policy_value_events"]}/8 预测分数改变，{visual_memory["native_committed_identity_changes"]}/8 改变后续身份，{visual_memory["non_tie_H64"]}/8 H64非平局。WRITE−KEEP 在 video13/F2/V1 为 H32−18/H64−13，在 video16/F17/V1 为 H32−73.25/H64−94.5，另外6次为平局。这证明记忆后果依赖实际后续策略；不是学会 MEMORY 的证据，也不能由原始OFF平局推断视觉模型中的记忆无效。','',
        '仅2个可靠锚定非平局 TRAIN 组、0个 VAL 组，低于事前12TRAIN/4VAL、各跨≥2视频的资格阈值。没有因该负/非平局结果调参、增加有利序列或训练伪标签。实际 stale pools 已记录，包括真实多候选/可靠 prefix anchors，但没有独立 TRAIN/VAL 的相反恢复动作及长期收益监督。MEMORY、REACTIVATION、共享三问题训练与 FULL_LIFECYCLE 均 NOT_RUN，继续 native fallback，指标 null。实际 stale typed input 修复使用真实 Gallery 长度、bank eligibility、消失时间与分数 entropy；专门的只读原生全状态核查 PASS。','',
        '硬件 Tesla V100-DGXS-32GB、PyTorch 2.0 / CUDA11.8、FP32、每个 actor CPU线程1。主矩阵为多 GPU 并行真实延迟；另在 GPU1 对事前 first/middle/last 各9个原生前缀进行基准。原始 Full 3种子 total token+policy+assignment p95：'+str([round(original_latency[f'full_s{s}']['total_policy_and_feature_ms']['p95'],3) for s in seeds])+' ms。字节一致的 metadata/历史 ID/视觉 token 批量化优化后：'+str([round(x,3) for x in fast_p95])+' ms，仍高于10ms；主视频矩阵没有切换优化实现。原始与优化的 max、p50、p95、显存、分阶段数据全部保留，优化中出现的长尾没有排除。','',
        '共享状态按当前 camera payload 一次 encode，服务该批所有 MATCH questions；跨 commit 的 state cache 不复用，命中0，MEM/REACT 保持原生规则，不冒称已训练网络时延。GMT Backbone 不重复执行，冻结感知直接复用。','',
        '## 十二个研究问题的明确回答','',
        '1. **是否是真实 State–Question–Option–Decision 结构？** 是。实际分层函数、cross-attention、动态问题门控、typed probability、masked options 与执行引用都在 forward/原生调用中；structural/gradient/行为/native tests PASS。结构成立不等于性能成立。','',
        '2. **QuestionReader 是动态的还是静态偏置？** 动态当前 ReID + context64 + task type 进入 Question-to-State reader。问题梯度、敏感性和相同证据不同正确动作任务（100% vs固定50%）提供功能证据；并未证明语言理解。','',
        '3. **OptionReader 是否读取具体动作与身份证据？** 是。真实 recent/first/mean、evidence12、own-question/state reads、候选竞争和 question-dependent tanh gate；排列等变且 ID 值不入 NN。单个问题的 cross-read 只有自身一个 question key，不声称在多个问题间选择注意力。','',
        '4. **一个共享模型支持三类接口吗？** 是，同一 State/Question/Option 参数处理三种合法空间；阶段状态在最终 ID commit 后重建。实际执行的 learned scope 只有 MATCH。当前版本 FULL_LIFECYCLE 明确拒绝启动，不允许传入三个字符串后静默伪装成已启用完整学习式生命周期；未来需合格监督和学习式 MEMORY/REACT 执行实现。','',
        '5. **三种问题均有真实监督吗？** 否。MATCH132/94与已执行 H8/16/32 有监督；MEM/REACT 不合格，维持 SHADOW/native fallback，共享训练未运行。','',
        f'6. **视觉 token 提供有效新增收益吗？** 尚不支持。Full 离线已确认正确 {offline["models"]["full"]["VALIDATION_mean"]["CertifiedCorrect"]*100:.2f}%，同架构 numerical_only {offline["models"]["numerical_only"]["VALIDATION_mean"]["CertifiedCorrect"]*100:.2f}%；完整视频结果已并列。不能由此断言视觉信息本身无用，结论限定于当前数据、架构与训练协议。','',
        f'7. **Full 优于容量/证据匹配 Set Transformer 吗？** 离线下界落后约{-known_delta["full_minus_baseline_certified_correct"]*100:.2f}点；严格在线 Full−Set HOTA {full_hota-set_hota:+.3f}。缺乏独立 heldout 结构优势证据，不能宣称 JEV 优于普通 Attention。','',
        f'8. **风险 fallback 降低实际错误关联风险吗？** 同权重、同温度的 risk on−off HOTA 为 {risk_delta:+.3f}，有有限改善。已确认错误观测均值 on {diagnostic_avg("full","confirmed_wrong_observations"):.1f} / off {diagnostic_avg("full_no_risk","confirmed_wrong_observations"):.1f}，两者的 UNKNOWN 范围不同；不能断言全面降险，也不代表独立 abstain 概率已校准，更没有恢复到 GMT OFF 水平。','',
        '9. **长期效用比普通相似度更有价值吗？** full/no_H32/no_consequence/similarity 三种子与真实视频比较全部提供；当前不具备长期效用导致在线性能优于传统 GMT 的证据。Q 标签来自执行过的有限分支与 GMT_OFF future，joint externalities 与未执行候选保持未知。','',
        f'10. **是否真实改善在线 HOTA/AssA？** 当前 Full−GMT OFF 为 HOTA {full_hota-off_hota:+.3f} / AssA {full_assa-off_assa:+.3f}，明显退化。所有当前/下一帧来自真实 native state 更新，不能用离线 Tiny100% 或部分标签 NLL 抵消这个负结果。','',
        '11. **符合在线部署要求吗？** 目前未达到新增决策 p95≤10ms。已实现真实共享与 batch读取、尝试字节一致 token优化并保留原始结果；没有用未来帧、改轻基线或去掉不利时延样本获得通过。','',
        '12. **目前可主张的 WWW 科学贡献？** 可主张可检查的动态视觉决策接口、原生因果状态/未知监督契约和闭环失败诊断；不能主张有竞争力的跟踪性能、结构显著优于同视觉注意力、三任务共同学会、商业 Jev/RLCD 复现。当前 MATCH 性能扩展 NO_GO。后续需要在独立设计中解决 corrective-sample 到完整在线分布、UNKNOWN 校准与 background-policy/feedback shift，重新事前冻结；不能用 sealed 视频调参。','',
        '## 为什么属于动态视觉 Jev 风格接口，而非改名','',
        '判据是 `encode_state → encode_questions → score_questions` 实际运算，以及共享状态被真实动态 Question、真实历史候选读取并由 question-conditioned gate 产生 typed action probabilities/Q，再提交到原生可变状态。模块 hook、梯度、相同状态不同问题功能任务、permutation、真实 commit/下一步候选和对应消融分别检查这些路径。旧 CandidateJEV 的两个静态8D向量/MLP仍列作旧对照。当前结构有充分可核验功能证据，当前研究没有支持其优越性的闭环证据。','',
        '## 工程修复与复核入口','',
        '所有早期失败与旧结果保留。训练前修正 legacy adapter 的 dynamic B×Q batching；正式视觉 MOT 前发现额外未训练 DEFER token 进入竞争池，停止新增任务并修正，使真实生产 tensor 与冻结训练 tensor 一致。DEFER 保留冻结私有 solver dummy，不伪造 terminal 监督；旧数值控制 fast path、GMT/Fixed结果经相同 checkpoint/case/source 检查复用。没有查看视觉 MOT 后修改网络或重训选有利种子。','',
        '脚本：`train_jev_phase12_match.py`、`queue_jev_phase12_online.py`、`run_jev_phase12_closed_loop.py`、`finalize_jev_phase12_online.py`、`finalize_jev_phase12_global_mcmot.py`、`audit_jev_phase12_lifecycle.py`、`benchmark_jev_phase12_latency.py`。冻结 source/parameter/config/dataset/checkpoint SHA 在各报告及 manifest；运行大文件本地保留，不提交 Git。审查先读 `FINAL_GO_NO_GO.json`、`MATCH_VALIDATION_RESULTS.json` 和 `LIFECYCLE_DATA_ELIGIBILITY.json`。','',
        '复现主矩阵需 checkout 精确 actor commit `40774754fcad13fef0ff240a6f305cbd33e026c9`，而不是直接用更新后的报告提交运行旧 ONLINE_PROTOCOL（其脚本 SHA 会正确拒绝不匹配）。25个早期已完成的 GMT/Fixed/旧数值控制来自 `d85fb508efaff8f34bc908d15afb76c826299cc1`，经等价策略与配置检查允许复用，其余143个来自4077475。正式51 fits源码为 `2e00194`。后续提交仅包含未训练 stale 输入语义修复、FULL显式拒绝、统计元数据修正、可选精确token优化及归因/交付工具，没有更新主矩阵的架构、参数、阈值或预测。','',
        'DELIVERY_INTEGRITY 复核168 actor/336预测文件 SHA、全部51 fits/102权重 SHA、两套56条件×2scope指标 SHA、主协议源码、GMT foundation、perception cache index、B2和历史报告。Heldout20/21/22保持封存。失败或中断证据在 EARLY_ENGINEERING_FAILURES 与本地日志保留；Git仅上传必要源码、紧凑结果/图表，不上传视觉数据、权重或原生快照。',''])
    (ROOT/'docs/JEV_PHASE12_FINAL_RESEARCH_REPORT.md').write_text('\n'.join(lines))
    save(REPORTS/'FINAL_ARTIFACTS_MANIFEST.json',{'status':'COMPLETE','source_commit_before_final_document_commit':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'source_files_SHA256':{str(p.relative_to(ROOT)):sha(p) for p in sorted(list((ROOT/'gtr/modeling/visual_jev_mcmot').glob('*.py'))+list((ROOT/'reproduction_tools').glob('*phase12*.py'))+[ROOT/'gtr/modeling/meta_arch/gtr_rcnn.py',ROOT/'gtr/config.py'])},'files_SHA256':{str(p.relative_to(ROOT)):sha(p) for p in sorted(list(REPORTS.glob('*.json'))+list((ROOT/'docs').glob('JEV_PHASE12*.md'))+list((ROOT/'docs/figures/JEV_PHASE12').glob('*'))) if p.name!='FINAL_ARTIFACTS_MANIFEST.json'},'required_json_reports':required+['ARCHITECTURE_FREEZE','FINAL_GO_NO_GO'],'no_large_binaries_uploaded':True,'weights_visual_dataset_native_prefixes_kept_local':True,'heldout':'SEALED','Full24':False,'official_TEST':False})
    print('ALL_REQUIRED_PHASE12_REPORTS_COMPLETE',flush=True)
if __name__=='__main__':main()
